export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_RELOAD_REQUEST = 'USER_RELOAD_REQUEST';
export const USER_RELOAD_SUCCESS = 'USER_RELOAD_SUCCESS';
export const USER_RELOAD_FAIL = 'USER_RELOAD_FAIL';

export const USER_PAY_REQUEST = 'USER_PAY_REQUEST';
export const USER_PAY_SUCCESS = 'USER_PAY_SUCCESS';
export const USER_PAY_FAIL = 'USER_PAY_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';